In [330]:
import torch
import torch.nn as nn

attention = nn.MultiheadAttention(3, 1)
attention

MultiheadAttention(
  (out_proj): NonDynamicallyQuantizableLinear(in_features=3, out_features=3, bias=True)
)

In [331]:
x = torch.randn(2, 3)
x

tensor([[-0.4958, -0.8534, -0.4214],
        [-0.8438,  0.1714, -0.6490]])

In [332]:
attention(x, x, x)

(tensor([[-0.3292, -0.0839, -0.0926],
         [-0.3436, -0.0839, -0.0979]], grad_fn=<SqueezeBackward1>),
 tensor([[0.5116, 0.4884],
         [0.4686, 0.5314]], grad_fn=<SqueezeBackward1>))

In [333]:
attention._parameters

OrderedDict([('in_proj_weight',
              Parameter containing:
              tensor([[-0.1405, -0.3945,  0.5471],
                      [-0.1265, -0.5828, -0.5495],
                      [-0.2209, -0.3847,  0.6708],
                      [ 0.1557, -0.6537,  0.5884],
                      [-0.3887, -0.2024, -0.5411],
                      [-0.1282,  0.2785,  0.5890],
                      [ 0.6437, -0.6600,  0.3784],
                      [-0.1468,  0.0951, -0.6093],
                      [-0.1017, -0.2700, -0.2403]], requires_grad=True)),
             ('q_proj_weight', None),
             ('k_proj_weight', None),
             ('v_proj_weight', None),
             ('in_proj_bias',
              Parameter containing:
              tensor([0., 0., 0., 0., 0., 0., 0., 0., 0.], requires_grad=True))])

In [334]:
z = (attention._parameters['in_proj_weight'] @ x.T)
Q, K, V = z[:3], z[3:6], z[6:]
Q, K, V

(tensor([[ 0.1757, -0.3041],
         [ 0.7916,  0.3635],
         [ 0.1551, -0.3148]], grad_fn=<SliceBackward0>),
 tensor([[ 0.2327, -0.6253],
         [ 0.5935,  0.6445],
         [-0.4224, -0.2264]], grad_fn=<SliceBackward0>),
 tensor([[ 0.0846, -0.9019],
         [ 0.2484,  0.5356],
         [ 0.3821,  0.1955]], grad_fn=<SliceBackward0>))

In [335]:
(Q @ K.T)

tensor([[ 0.2310, -0.0917, -0.0054],
        [-0.0430,  0.7041, -0.4166],
        [ 0.2330, -0.1108,  0.0058]], grad_fn=<MmBackward0>)